### ISSUE TITLE
Doubt on missing values and/or zero values

### ISSUE THREAD

**Issue by Gelso22** [CNIC92/beat-the-stock-market#1]
Hello! Sorry for writing here but I didn't find a better way to contact you.
Thank you for the big dataset you offered on kaggle about stock market. 
I am doing a project about that for the university. 

Can I ask you, when you were pullinng the data, the origin of the difference between NA and zero values?

I don't know how to consider zero values. Maybe some are real zeros maybe some can be treathed as NA?
Thank you if you read!

**Comment by CNIC92** [comment]
> Hello! Sorry for writing here but I didn't find a better way to contact you. Thank you for the big dataset you offered on kaggle about stock market. I am doing a project about that for the university.
> 
> Can I ask you, when you were pullinng the data, the origin of the difference between NA and zero values?
> 
> I don't know how to consider zero values. Maybe some are real zeros maybe some can be treathed as NA? Thank you if you read!


Good question, let me think.

**About the NAs**
I would think that NAs are always missing value, plain and simple. You can either drop or fill them, up to you.

**About the 0s**
It could be that when they parsed the financial statements and didn't get some values, they used 0s as fillers.

- If you have the time and energy, you could set some rules for handling 0s differently depending on the column (like stock price=0 makes no sense, but some indicators might actually be 0 because of specific conditions). You could also check it by yourself, by looking for the 0 value here [https://www.sec.gov/dera/data/financial-statement-and-notes-data-set.html](https://www.sec.gov/dera/data/financial-statement-and-notes-data-set.html).
- If you don't have the time and energy, just skip them.

As a general rule, I would not recommend a _brute-force_ replacement of the 0s with some mean of ffill or whatever, at least not if you're unsure about what 0 means for that column.

**Comment by Gelso22** [comment]
Thank you for your answer.
I will probably just leave the zeros and impute the missing values. Maybe later I will test model performance even with 0 values as NA so imputed. 
But yes.. for some index/metrix actually zero is probably the real value.
